project:
  type: book
  
lang: pt-BR

book:
  title: "Análise Inferencial"
  subtitle: "Departamento de Estatística e Matemática Aplicada"
  description: "Laboratório de Inovação em Estatística - StatLab"
  author: "Manoel Santos-Neto"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - unidade1.qmd
    - unidade2.qmd
    - unidade3.qmd
    - unidade4.qmd
    - unidade5.qmd
    - unidade6.qmd
    - unidade7.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
  pdf:
    documentclass: scrreprt
    pdf-engine: lualatex
    include-in-header: macros.tex

editor: visual



